server:
  port: 8080
  servlet:
    session:
      timeout: 60

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///club_system?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  application:
    name: service-core
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 10000
  jackson:
    time-zone: GMT+8

logging:
  level:
    com:
      springboot: error

rsa:
  key:
    privateKeyFile: ./src/main/resources/id_rsa_private_key.key
    publicKeyFile: ./src/main/resources/id_rsa_public_key.pub
    secret: (EMOK:)_$^11244^%$_(IS:)_@@++--(COOL:)_++++_.sds_(GUY:)

file:
  url: /files/**
  host: http://127.0.0.1:${server.port}/files/
